# MYSQL Configuration
db.url=jdbc:mysql://localhost:3306/transaction_limit_db
db.username=root
db.password=Thyags@mysql
db.driver=com.mysql.cj.jdbc.Driver

# HikariCP Configuration
hikari.pool.name=TransactionPool
hikari.maxPoolSize=10
hikari.minIdle=2
hikari.idleTimeout=30000
hikari.maxLifetime=1800000
hikari.connectionTimeout=30000